### ISSUE TITLE
Endpoints not getting Generated

### ISSUE THREAD

**Issue by soumakpoddar** [anupsaund/vertx-auto-swagger#1]
Hi @anupsaund , great initiative first of all. I had an issue, like the endpoints are not being generated. Can you help me to resolve it. I have attached the image here.

<img width="1792" alt="Screenshot 2022-02-01 at 3 34 39 PM" src="https://user-images.githubusercontent.com/45389833/151949152-41f20fc8-22df-4a0e-95b3-e5b34d19200b.png">

**Comment by anupsaund** [comment]
@soumakpoddar - Sure thing, it's been a while since I worked on this project.

If you give me a few days - I'll take a look and then get back to you.

**Comment by soumakpoddar** [comment]
> @soumakpoddar - Sure thing, it's been a while since I worked on this project.
> 
> If you give me a few days - I'll take a look and then get back to you.

Hi @anupsaund sure thanks a lot. Just in case you need my implementation here it is - [Repo Link](https://github.com/soumakpoddar/MMT-Todo)

**Comment by anupsaund** [comment]
Running the existing project is OK.

<img width="700" alt="current" src="https://user-images.githubusercontent.com/6728822/152288567-b2e8aa80-d880-45e7-97e1-9898efe7dd7e.png">

Running MMT_Induction, debugging...

src/main/java/generator/OpenApiSpecGenerator.java
Line 67.

<img width="903" alt="BreakPoint" src="https://user-images.githubusercontent.com/6728822/152288908-2f560503-7b01-4cc6-91e8-f2cdcc26e138.png">

It looks like the contextHandlers is missing from the route...

<img width="699" alt="Missing Field" src="https://user-images.githubusercontent.com/6728822/152288993-e2f72f4f-9a40-485c-bbb3-67f95c2bc187.png">

The try catch, masks the issue and we end up with no routes in the Swagger UI.

The next thing to do would be to trace the stack to see where and why the field is missing.

Over to you.

**Comment by anupsaund** [comment]
I think it's because the vert.x version is newer..

`<vertx.version>4.2.3</vertx.version>`

vs

`<vertx.version>3.5.3</vertx.version>`

I believe a lot has changed since 3.5.3 that would need upgrading.

Consider, upgrading the code base implementation or downgrading the vert.x framework.

**Comment by soumakpoddar** [comment]
Hi @anupsaund thanks for your help....I tried downgrading vert.x but it didn't work. I guess the error is in that src/main/java/generator/OpenApiSpecGenerator.java line 67. I tried stacktracing it. I think update should be needed. I have attached the image of the stacktrace. If you find any solution please help me......Thanks a lot for your time.....

![image](https://user-images.githubusercontent.com/45389833/152316557-137e5d0a-b589-4745-b290-7fd5ac50dcb1.png)

**Comment by soumakpoddar** [comment]
Hi @anupsaund thanks a lot. We have updated it according to Vert.x version 4. It can be found [here](https://github.com/soumakpoddar/MMT-Todo).

**Comment by anupsaund** [comment]
Thanks @soumakpoddar - I went ahead and back ported the changes into my project and upgraded vert.x.

Works great!

Thanks for the collaboration.

**Comment by soumakpoddar** [comment]
Thanks to you @anupsaund for making lives easier with this great tool....👍✌️
